version: "3.9"

services:
    nginx:
        container_name: nginx
        build: ./.docker/nginx
        ports:
            - "80:80"
        volumes:
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html
        depends_on:
            - php
    php:
        container_name: php
        build: ./.docker/php
        ports:
            - "9000:9000"
        volumes:
            - ./:/var/www/html
            - ./docker/app/php.ini:/usr/local/etc/php/php.ini
        depends_on:
            - db
    db:
        container_name: db
        build: ./.docker/db
        restart: always
        volumes:
            - ./.docker/db/.data:/var/lib/postgresql/data
            - ./.docker/db/postgresql.conf:/etc/postgresql/postgresql.conf
        environment:
            POSTGRES_PASSWORD: testapi-sys
            POSTGRES_USER: testapi-sys
            POSTGRES_DB: testapi-sys
        command: -c 'config_file=/etc/postgresql/postgresql.conf'
        ports:
            - "5432:5432"
    node:
        container_name: node
        build: ./.docker/node
        working_dir: /usr/src/app
        tty: true
        ports:
            - "5173:5173"
        volumes:
            - ./:/usr/src/app
    ngrok:
        container_name: ngrok
        image: wernight/ngrok:latest
        ports:
            - ${NGROK_PORT:-4040}:4040
        environment:
            NGROK_PORT: nginx:80
            NGROK_AUTH: 2GKecHKvU3MYxnmz8yI7KcDUL17_4JFG78YMQ3xAViKbWSmnn
